export const SellerFilesData = [
  {
    id:"1",
    ID: "#120",
    Uploaded_For:
      "I will do designing and executing targeted email\n                              campaigns",
      Image:"gigs-09.jpg",
    Uploaded_On: "22 May 2023",
    Uploaded_By: "James Carter",
    UserImage:"user-01.jpg",
    File_Type: "Jpg",
    Action: "",
  },
  {
    id:"2",
    ID: "#119",
    Uploaded_For:
      "I will develop openai, dalle, chat gpt app for\n                              mobile",
      Image:"gigs-03.jpg",
    Uploaded_On: "20 May 2023",
    Uploaded_By: "Michael Reynolds",
    UserImage:"user-02.jpg",
    File_Type: "Mp4",
    Action: "",
  },
  {
    id:"3",
    ID: "#118",
    Uploaded_For:
      "I will do professional lifestyle and product\n                              photography",
      Image:"gigs-02.jpg",
    Uploaded_On: "15 May 2023",
    Uploaded_By: "Emily Sanders",
    UserImage:"user-03.jpg",
    File_Type: "Png",
    Action: "",
  },
  {
    id:"4",
    ID: "#117",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Image:"gigs-04.jpg",
    Uploaded_On: "27 Apr 2023",
    Uploaded_By: "David Lawson",
    UserImage:"user-04.jpg",
    File_Type: "Png",
    Action: "",
  },
  {
    id:"5",
    ID: "#116",
    Uploaded_For:
      "I will do creating and promoting video content to\n                              engage audiences",
      Image:"gigs-13.jpg",
    Uploaded_On: "19 Apr 2023",
    Uploaded_By: "Ryan Mitchell",
    UserImage:"user-05.jpg",
    File_Type: "Png",
    Action: "",
  },
  {
    id:"6",
    ID: "#115",
    Uploaded_For:
      "I will do implementing chatbots on websites or\n                              messaging apps",
      Image:"gigs-05.jpg",
    Uploaded_On: "03 Apr 2023",
    Uploaded_By: "Jason Brooks",
    UserImage:"user-06.jpg",
    File_Type: "MP4",
    Action: "",
  },
  {
    id:"7",
    ID: "#120",
    Uploaded_For:
      "I will develop openai, dalle, chat gpt app for\n                              mobile",
      Image:"gigs-03.jpg",
    Uploaded_On: "20 May 2023",
    Uploaded_By: "Thomas Bennett",
    UserImage:"user-02.jpg",
    File_Type: "Mp4",
    Action: "",
  },
  {
    id:"8",
    ID: "#121",
    Uploaded_For:
      "I will do professional lifestyle and product\n                              photography",
      Image:"gigs-02.jpg",
    Uploaded_On: "15 May 2023",
    Uploaded_By: "Sophia Collins",
    UserImage:"user-03.jpg",
    File_Type: "Png",
    Action: "",
  },
  {
    id:"9",
    ID: "#122",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Image:"gigs-04.jpg",
    Uploaded_On: "27 Apr 2023",
    Uploaded_By: "Thomas Bennett",
    UserImage:"user-04.jpg",
    File_Type: "Png",
    Action: "",
  },
  {
    id:"10",
    ID: "#123",
    Uploaded_For:
      "I will do creating and promoting video content to\n                              engage audiences",
      Image:"gigs-13.jpg",
    Uploaded_On: "19 Apr 2023",
    Uploaded_By: "Ryan Mitchell",
    UserImage:"user-05.jpg",
    File_Type: "Png",
    Action: "",
  },
  {
    id:"11",
    ID: "#124",
    Uploaded_For:
      "I will do implementing chatbots on websites or\n                              messaging apps",
      Image:"gigs-05.jpg",
    Uploaded_On: "03 Apr 2023",
    Uploaded_By: "Hendy",
    UserImage:"user-06.jpg",
    File_Type: "MP4",
    Action: "",
  },
];
