export const BuyerWalletData = [
  {
    id:"1",
    ID: "#WT120",
    Uploaded_For:"I will do designing and executing targeted email\n                          campaigns",
    Image:"gigs-09.jpg",
    Payment_Gateway: "Paypal",
    Date_Time: "22 May 2023 10:50PM",
    Type: "Debit",
    Amount: "-$154",
  },
  {
    id:"2",
    ID: "#WT119",
    Uploaded_For: "I will develop openai, dalle, chat gpt app for mobile",
    Image:"gigs-03.jpg",
    Payment_Gateway: "Stripe",
    Date_Time: "21 May 2023 11:25 PM",
    Type: "Credit",
    Amount: "+$1154",
  },
  {
    id:"3",
    ID: "#WT118",
    Uploaded_For:"I will do professional lifestyle and product\n                          photography",
    Image:"gigs-02.jpg",
    Payment_Gateway: "Paypal",
    Date_Time: "17 May 2023 12:16 AM",
    Type: "Credit",
    Amount: "+$6547",
  },
  {
    id:"4",
    ID: "#WT117",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Image:"gigs-04.jpg",
    Payment_Gateway: "Stripe",
    Date_Time: "15 May 2023 11:21 PM",
    Type: "Credit",
    Amount: "+$1454",
  },
  {
    id:"5",
    ID: "#WT116",
    Uploaded_For:'I will do creating and promoting video content to\n                          engage audiences',
    Image:"gigs-01.jpg",
    Payment_Gateway: "Paypal",
    Date_Time: "17 Feb 2025 10:50 PM",
    Type: "Debit",
    Amount: "+$1454",
  },
  {
    id:"6",
    ID: "#WT115",
    Uploaded_For:"I will do implementing chatbots on websites or\n                          messaging apps",
    Image:"gigs-09.jpg",
    Payment_Gateway: "Stripe",
    Date_Time: "02 Feb 2025 10:04 PM",
    Type: "Credit",
    Amount: "+$1454",
  },
  {
    id:"7",
    ID: "#WT114",
    Uploaded_For:'I will develop openai, dalle, chat gpt app for mobile',
    Image:"gigs-03.jpg",
    Payment_Gateway: "Paypal",
    Date_Time: "29 Jan 2025 03:50 PM",
    Type: "Debit",
    Amount: "-$545",
  },
  {
    id:"8",
    ID: "#WT113",
    Uploaded_For:"I will do professional lifestyle and product\n                          photography",
    Image:"gigs-11.jpg",
    Payment_Gateway: "Stripe",
    Date_Time: "15 Jan 2025 05:50 AM",
    Type: "Debit",
    Amount: "-$545",
  },
  {
    id:"9",
    ID: "#WT112",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Image:"gigs-14.jpg",
    Payment_Gateway: "Paypal",
    Date_Time: "12 Jan 2025 09:15 AM",
    Type: "Debit",
    Amount: "-$545",
  },
  {
    id:"10",
    ID: "#WT111",
    Uploaded_For:
      "I will do creating and promoting video content to\n                          engage audiences",
      Image:"gigs-13.jpg",
    Payment_Gateway: "Stripe",
    Date_Time: "05 Jan 2025 10:50 PM",
    Type: "Credit",
    Amount: "+$545",
  },
];
