export const BuyerPurchaseData = [
  {
    id:"1",
    ID: "#PR120",
    Uploaded_For: "I will do designing and executing targeted email campaigns",
    Image:"gigs-01.jpg",
    Purchase_On: "22 Mar 2025",
    Seller: "Isla Harrington",
    Seller_Image:"user-08.jpg",
    Feedback: "Write Review",
    Cancel: "Cancel",
    Amount: "$2000",
    Payment_Mode: "Wallet",
    Status: "New",
    Action: "",
  },
  {
    id:"2",
    ID: "#PR119",
    Uploaded_For: "I will develop openai, dalle, chat gpt app for mobile",
    Image:"gigs-02.jpg",
    Purchase_On: "18 Mar 2025",
    Seller: "Ethan Mercer",
    Seller_Image:"user-02.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2600",
    Payment_Mode: "Paypal",
    Status: "Processing",
    Action: "",
  },
  {
    id:"3",
    ID: "#PR118",
    Uploaded_For: "I will do professional lifestyle and product photography",
    Image:"gigs-03.jpg",
    Purchase_On: "06 Mar 2025",
    Seller: "Mira Caldwell",
    Seller_Image:"user-03.jpg",
    Feedback: "View",
    Cancel: "Cancel",
    Amount: "$1800",
    Payment_Mode: "Wallet",
    Status: "Pending",
    Action: "",
  },
  {
    id:"4",
    ID: "#PR117",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Image:"gigs-04.jpg",
    Purchase_On: "26 Feb 2025",
    Seller: "Julian Hayes",
    Seller_Image:"user-04.jpg",
    Feedback: "View",
    Cancel: "Cancel",
    Amount: "$2700",
    Payment_Mode: "COD",
    Status: "New",
    Action: "",
  },
  {
    id:"5",
    ID: "#PR116",
    Uploaded_For: "I will do creating and promoting video content to engage audiences",
    Image:"gigs-05.jpg",
    Purchase_On: "17 Feb 2025",
    Seller: "Maxwell Thornton",
    Seller_Image:"user-05.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2000",
    Payment_Mode: "Paypal",
    Status: "Completed",
    Action: "",
  },
  {
    id:"6",
    ID: "#PR115",
    Uploaded_For:"I will do implementing chatbots on websites or messaging apps",
    Image:"gigs-06.jpg",
    Purchase_On: "02 Feb 2025",
    Seller: "Tessa Langley",
    Seller_Image:"user-10.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2600",
    Payment_Mode: "Wallet",
    Status: "Processing",
    Action: "",
  },
  {
    id:"7",
    ID: "#PR114",
    Uploaded_For: "I will develop openai, dalle, chat gpt app for mobile",
    Image:"gigs-07.jpg",
    Purchase_On: "29 Jan 2025",
    Seller: "Noelle Vance",
    Seller_Image:"user-13.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$1800",
    Payment_Mode: "Wallet",
    Status: "Pending",
    Action: "",
  },
  {
    id:"8",
    ID: "#PR113",
    Uploaded_For: "I will do professional lifestyle and product photography",
    Image:"gigs-08.jpg",
    Purchase_On: "15 Jan 2025",
    Seller: "Caleb Sutton",
    Seller_Image:"user-18.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2700",
    Payment_Mode: "Paypal",
    Status: "Completed",
    Action: "",
  },
  {
    id:"9",
    ID: "#PR112",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Image:"gigs-09.jpg",
    Purchase_On: "12 Jan 2025",
    Seller: "Lucas Davenport",
    Seller_Image:"user-16.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2000",
    Payment_Mode: "COD",
    Status: "Processing",
    Action: "",
  },
  {
    id:"10",
    ID: "#PR111",
    Uploaded_For:"I will do creating and promoting video content to engage audiences",
    Image:"gigs-10.jpg",
    Purchase_On: "05 Jan 2025",
    Seller: "Selene Draper",
    Seller_Image:"user-12.jpg",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$1800",
    Payment_Mode: "Wallet",
    Status: "New",
    Action: "",
  },
];
