export const sellerPayoutsData = [
  {
    key: "1",
    Date_Time: "22 Mar 2025 10:50 PM",
    Payment_Gateway: "Paypal",
    Amount: "-$45",
    Status: "Completed",
  },
  {
    key: "2",
    Date_Time: "18 Mar 2025 11:30 PM",
    Payment_Gateway: "Stripe",
    Amount: "-$145",
    Status: "Completed",
  },
  {
    key: "3",
    Date_Time: "22 Mar 2025 10:50 PM",
    Payment_Gateway: "Paypal",
    Amount: "-$45",
    Status: "Completed",
  },
  {
    key: "4",
    Date_Time: "18 Mar 2025 11:30 PM",
    Payment_Gateway: "Stripe",
    Amount: "-$145",
    Status: "Completed",
  },
  {
    key: "5",
    Date_Time: "22 Mar 2025 10:50 PM",
    Payment_Gateway: "Paypal",
    Amount: "-$45",
    Status: "Completed",
  },
  {
    key: "6",
    Date_Time: "18 Mar 2025 11:30 PM",
    Payment_Gateway: "Stripe",
    Amount: "-$145",
    Status: "Completed",
  },
  {
    key: "7",
    Date_Time: "22 Mar 2025 10:50 PM",
    Payment_Gateway: "Paypal",
    Amount: "-$45",
    Status: "Completed",
  },
  {
    key: "8",
    Date_Time: "18 Mar 2025 11:30 PM",
    Payment_Gateway: "Stripe",
    Amount: "-$145",
    Status: "Completed",
  },
  {
    key: "9",
    Date_Time: "22 Mar 2025 10:50 PM",
    Payment_Gateway: "Paypal",
    Amount: "-$45",
    Status: "Completed",
  },
  {
    key: "10",
    Date_Time: "18 Mar 2025 11:30 PM",
    Payment_Gateway: "Stripe",
    Amount: "-$145",
    Status: "Completed",
  },
];
