export const sellerEarningsData = [
  {
    key: "1",
    ID: "#ER120",
    Image: "gigs-09.jpg",
    Uploaded_For: "I will do designing and executing targeted email campaigns",
    Payment_Type: "Paypal",
    Amount: "-$45",
  },
  {
    key: "2",
    ID: "#ER119",
    Image: "gigs-10.jpg",
    Uploaded_For: "I will do designing and executing...",
    Payment_Type: "Stripe",
    Amount: "-$65",
  },
  {
    key: "3",
    ID: "#ER118",
    Image: "gigs-02.jpg",
    Uploaded_For: "I will develop openai, dalle, chat gpt app for mobile",
    Payment_Type: "Paypal",
    Amount: "-$45",
  },
  {
    key: "4",
    ID: "#ER117",
    Image: "gigs-03.jpg",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Payment_Type: "Stripe",
    Amount: "-$95",
  },
  {
    key: "5",
    ID: "#ER116",
    Image: "gigs-07.jpg",
    Uploaded_For: "I will do creating and promoting video content to engage audiences",
    Payment_Type: "Paypal",
    Amount: "-$25",
  },
  {
    key: "6",
    ID: "#ER115",
    Image: "gigs-12.jpg",
    Uploaded_For: "I will do implementing chatbots on websites or messaging apps",
    Payment_Type: "Stripe",
    Amount: "-$65",
  },
  {
    key: "7",
    ID: "#ER114",
    Image: "gigs-15.jpg",
    Uploaded_For: "I will develop openai, dalle, chat gpt app for mobile",
    Payment_Type: "Paypal",
    Amount: "-$97",
  },
  {
    key: "8",
    ID: "#ER113",
    Image: "gigs-13.jpg",
    Uploaded_For: "I will do professional lifestyle and product photography",
    Payment_Type: "Stripe",
    Amount: "-$45",
  },
  {
    key: "9",
    ID: "#ER112",
    Image: "gigs-01.jpg",
    Uploaded_For: "Embedded Android & AOSP customizations",
    Payment_Type: "Paypal",
    Amount: "-$45",
  },
  {
    key: "10",
    ID: "#ER111",
    Image: "gigs-09.jpg",
    Uploaded_For: "I will do creating and promoting video content to engage audiences",
    Payment_Type: "Stripe",
    Amount: "-$45",
  },
];
