export const sellerOrdersData = [
  {
    key: "1",
    ID: "#OD120",
    Gigs: "Designing and developing...",
    Delivery_On: "02 May 2025",
    Image: "user-08.jpg",
    Buyer: "James Carter",
    Feedback: "Write Review",
    Cancel: "Cancel",
    Amount: "$2000",
    Payment_Mode: "Wallet",
    Status: "New",
    Action: "",
  },
  {
    key: "2",
    ID: "#OD119",
    Gigs: "I will do professional lifest...",
    Delivery_On: "18 Mar 2025",
    Image: "user-02.jpg",
    Buyer: "Ethan Mercer",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2600",
    Payment_Mode: "Paypal",
    Status: "Processing",
    Action: "",
  },
  {
    key: "3",
    ID: "#OD118",
    Gigs: "I will develop openai, dalle..",
    Delivery_On: "06 Mar 2025",
    Image: "user-03.jpg",
    Buyer: "Mira Caldwell",
    Feedback: "View",
    Cancel: "Cancel",
    Amount: "$1800",
    Payment_Mode: "Wallet",
    Status: "Pending",
    Action: "",
  },
  {
    key: "4",
    ID: "#OD117",
    Gigs: "Embedded Android & AO...",
    Delivery_On: "26 Feb 2025",
    Image: "user-04.jpg",
    Buyer: "Julian Hayes",
    Feedback: "View",
    Cancel: "Cancel",
    Amount: "$2700",
    Payment_Mode: "Cod",
    Status: "New",
    Action: "",
  },
  {
    key: "5",
    ID: "#OD116",
    Gigs: "I will do implementing cha...",
    Delivery_On: "17 Feb 2025",
    Image: "user-05.jpg",
    Buyer: "Maxwell Thornton",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2000",
    Payment_Mode: "Paypal",
    Status: "Completed",
    Action: "",
  },
  {
    key: "6",
    ID: "#OD115",
    Gigs: "Managing and optimizing...",
    Delivery_On: "02 Feb 2025",
    Image: "user-10.jpg",
    Buyer: "Tessa Langley",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2600",
    Payment_Mode: "Wallet",
    Status: "Processing",
    Action: "",
  },
  {
    key: "7",
    ID: "#OD114",
    Gigs: "I will do collaborating with..",
    Delivery_On: "29 Jan 2025",
    Image: "user-13.jpg",
    Buyer: "Noelle Vance",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$1800",
    Payment_Mode: "Wallet",
    Status: "Pending",
    Action: "",
  },
  {
    key: "8",
    ID: "#OD113",
    Gigs: "I will do professional lifest...",
    Delivery_On: "15 Jan 2025",
    Image: "user-18.jpg",
    Buyer: "Caleb Sutton",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2700",
    Payment_Mode: "Paypal",
    Status: "Completed",
    Action: "",
  },
  {
    key: "9",
    ID: "#OD112",
    Gigs: "Embedded Android & AO...",
    Delivery_On: "12 Jan 2025",
    Image: "user-16.jpg",
    Buyer: "Lucas Davenport",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$2000",
    Payment_Mode: "Cod",
    Status: "Processing",
    Action: "",
  },
  {
    key: "10",
    ID: "#OD112",
    Gigs: "Managing and optimizing...",
    Delivery_On: "05 Jan 2025",
    Image: "user-12.jpg",
    Buyer: "Selene Draper",
    Feedback: "Pending",
    Cancel: "Cancel",
    Amount: "$1800",
    Payment_Mode: "Wallet",
    Status: "New",
    Action: "",
  },
];
