import type { Provider } from '../../../services/providerService';
import talentPlaceholder from '../../../assets/img/homepage/talent-placeholder.webp';

export interface TalentData extends Provider {
  country: string;
  ageGroup: string;
}

export const FILTER_OPTIONS = {
  sport: ['Football', 'Handball', 'Boxe', 'Basketball', 'Taekwondo', 'Athlétisme'],
  country: ['France', 'Belgique', 'Sénégal', 'Côte d\'Ivoire', 'Cameroun'],
  ageGroup: ['12-14 ans', '15-17 ans', '18-21 ans', '22-25 ans', '+25 ans'],
};

export const mockTalents: TalentData[] = [
  {
    id: 101,
    name: 'Amadou Diallo',
    firstName: 'Amadou',
    lastName: 'Diallo',
    email: 'amadou@example.com',
    avatar: talentPlaceholder,
    location: 'Paris',
    country: 'France',
    ageGroup: '22-25 ans',
    category: 'Football',
    price: 45,
    rating: 4.9,
    reviewCount: 87,
    isTopPrestataire: true,
    bio: "Attaquant professionnel avec 10 ans d'experience en club et selection nationale.",
    specialties: 'Technique\nVitesse\nFinition',
    portfolio: [],
    registeredDate: '2024-01-15',
    missionsCount: 42,
    responseTime: '~2h',
  },
  {
    id: 102,
    name: 'Sarah Koné',
    firstName: 'Sarah',
    lastName: 'Koné',
    email: 'sarah@example.com',
    avatar: talentPlaceholder,
    location: 'Lyon',
    country: 'France',
    ageGroup: '18-21 ans',
    category: 'Handball',
    price: 35,
    rating: 4.7,
    reviewCount: 54,
    isTopPrestataire: false,
    bio: 'Gardienne de but, selection nationale U21.',
    specialties: 'Reflexes\nLeadership',
    portfolio: [],
    registeredDate: '2024-03-20',
    missionsCount: 28,
    responseTime: '~4h',
  },
  {
    id: 103,
    name: 'Moussa Traoré',
    firstName: 'Moussa',
    lastName: 'Traoré',
    email: 'moussa@example.com',
    avatar: talentPlaceholder,
    location: 'Marseille',
    country: 'France',
    ageGroup: '+25 ans',
    category: 'Boxe',
    price: 55,
    rating: 5.0,
    reviewCount: 112,
    isTopPrestataire: true,
    bio: 'Champion regional de boxe anglaise, 15 combats professionnels.',
    specialties: 'Puissance\nEndurance\nStrategie',
    portfolio: [],
    registeredDate: '2023-11-10',
    missionsCount: 65,
    responseTime: '~1h',
  },
  {
    id: 104,
    name: 'Fatou Bamba',
    firstName: 'Fatou',
    lastName: 'Bamba',
    email: 'fatou@example.com',
    avatar: talentPlaceholder,
    location: 'Toulouse',
    country: 'France',
    ageGroup: '22-25 ans',
    category: 'Basketball',
    price: 40,
    rating: 4.8,
    reviewCount: 73,
    isTopPrestataire: true,
    bio: 'Meneuse de jeu en premiere division feminine.',
    specialties: 'Dribble\nVision de jeu\nPasses',
    portfolio: [],
    registeredDate: '2024-02-01',
    missionsCount: 36,
    responseTime: '~3h',
  },
  {
    id: 105,
    name: 'Ibrahim Cissé',
    firstName: 'Ibrahim',
    lastName: 'Cissé',
    email: 'ibrahim@example.com',
    avatar: talentPlaceholder,
    location: 'Bordeaux',
    country: 'Sénégal',
    ageGroup: '18-21 ans',
    category: 'Taekwondo',
    price: 50,
    rating: 4.6,
    reviewCount: 41,
    isTopPrestataire: false,
    bio: 'Ceinture noire 3eme dan, competiteur international.',
    specialties: 'Technique de pied\nSouplesse',
    portfolio: [],
    registeredDate: '2024-05-12',
    missionsCount: 19,
    responseTime: '~6h',
  },
  {
    id: 106,
    name: 'Aisha Ouédraogo',
    firstName: 'Aisha',
    lastName: 'Ouédraogo',
    email: 'aisha@example.com',
    avatar: talentPlaceholder,
    location: 'Lille',
    country: 'Côte d\'Ivoire',
    ageGroup: '22-25 ans',
    category: 'Athlétisme',
    price: 38,
    rating: 4.9,
    reviewCount: 95,
    isTopPrestataire: true,
    bio: 'Sprinteuse 100m et 200m, recordwoman regionale.',
    specialties: 'Vitesse\nExplosivite\nDemarrage',
    portfolio: [],
    registeredDate: '2023-09-01',
    missionsCount: 51,
    responseTime: '~2h',
  },
  {
    id: 107,
    name: 'Youssef Benali',
    firstName: 'Youssef',
    lastName: 'Benali',
    email: 'youssef@example.com',
    avatar: talentPlaceholder,
    location: 'Nantes',
    country: 'Belgique',
    ageGroup: '18-21 ans',
    category: 'Football',
    price: 42,
    rating: 4.5,
    reviewCount: 63,
    isTopPrestataire: false,
    bio: 'Milieu de terrain createur, formé en centre de formation professionnel.',
    specialties: 'Passes longues\nVision\nEndurance',
    portfolio: [],
    registeredDate: '2024-04-08',
    missionsCount: 31,
    responseTime: '~5h',
  },
  {
    id: 108,
    name: 'Marie Dupont',
    firstName: 'Marie',
    lastName: 'Dupont',
    email: 'marie@example.com',
    avatar: talentPlaceholder,
    location: 'Strasbourg',
    country: 'France',
    ageGroup: '15-17 ans',
    category: 'Handball',
    price: 33,
    rating: 4.7,
    reviewCount: 48,
    isTopPrestataire: false,
    bio: 'Arriere gauche, equipe regionale senior.',
    specialties: 'Tir\nContre-attaque',
    portfolio: [],
    registeredDate: '2024-06-15',
    missionsCount: 22,
    responseTime: '~4h',
  },
  {
    id: 109,
    name: 'Ousmane Diop',
    firstName: 'Ousmane',
    lastName: 'Diop',
    email: 'ousmane@example.com',
    avatar: talentPlaceholder,
    location: 'Dakar',
    country: 'Sénégal',
    ageGroup: '15-17 ans',
    category: 'Football',
    price: 30,
    rating: 4.3,
    reviewCount: 29,
    isTopPrestataire: false,
    bio: 'Jeune defenseur central avec un excellent jeu de tete.',
    specialties: 'Defense\nJeu aerien\nRelance',
    portfolio: [],
    registeredDate: '2024-07-01',
    missionsCount: 12,
    responseTime: '~8h',
  },
  {
    id: 110,
    name: 'Kevin Mbarga',
    firstName: 'Kevin',
    lastName: 'Mbarga',
    email: 'kevin@example.com',
    avatar: talentPlaceholder,
    location: 'Douala',
    country: 'Cameroun',
    ageGroup: '18-21 ans',
    category: 'Boxe',
    price: 48,
    rating: 4.8,
    reviewCount: 67,
    isTopPrestataire: true,
    bio: 'Boxeur poids moyen, triple champion regional.',
    specialties: 'Puissance\nVitesse\nEsquive',
    portfolio: [],
    registeredDate: '2024-01-20',
    missionsCount: 38,
    responseTime: '~3h',
  },
  {
    id: 111,
    name: 'Lucas Van der Berg',
    firstName: 'Lucas',
    lastName: 'Van der Berg',
    email: 'lucas@example.com',
    avatar: talentPlaceholder,
    location: 'Bruxelles',
    country: 'Belgique',
    ageGroup: '12-14 ans',
    category: 'Basketball',
    price: 25,
    rating: 4.2,
    reviewCount: 18,
    isTopPrestataire: false,
    bio: 'Jeune espoir du basketball belge, selection nationale U14.',
    specialties: 'Dribble\nTir a 3 points',
    portfolio: [],
    registeredDate: '2024-09-01',
    missionsCount: 8,
    responseTime: '~12h',
  },
  {
    id: 112,
    name: 'Aya Touré',
    firstName: 'Aya',
    lastName: 'Touré',
    email: 'aya@example.com',
    avatar: talentPlaceholder,
    location: 'Abidjan',
    country: 'Côte d\'Ivoire',
    ageGroup: '18-21 ans',
    category: 'Athlétisme',
    price: 35,
    rating: 4.6,
    reviewCount: 52,
    isTopPrestataire: false,
    bio: 'Specialiste du 400m haies, espoir olympique.',
    specialties: 'Endurance\nTechnique de haies\nRythme',
    portfolio: [],
    registeredDate: '2024-03-15',
    missionsCount: 25,
    responseTime: '~5h',
  },
];
